// AUTO-GENERATED dari prisma/data/lokasi-awal.json (impor lokasi_awal.xlsx).
// Data master lokasi awal — di-embed sbg modul TS agar tersedia di dev & container
// standalone tanpa bergantung path filesystem saat seed.
export type LokasiAwalRow = {
  province: string;
  regency: string;
  district: string | null;
  village: string;
  latitude: number | null;
  longitude: number | null;
  candidateVendor: string;
};

export const LOKASI_AWAL: LokasiAwalRow[] = [
  {"province":"Jawa Tengah","regency":"Brebes","district":"Tanjung","village":"Pengaradan","latitude":-6.847202,"longitude":108.8789,"candidateVendor":"CV. Alkomber Karya"},
  {"province":"Jawa Tengah","regency":"Brebes","district":"Tanjung","village":"Krakahan","latitude":-6.847928598,"longitude":108.8859467,"candidateVendor":"CV. Alkomber Karya"},
  {"province":"Jawa Timur","regency":"Malang","district":"Donomulyo","village":"Kedungsalam","latitude":-8.380833,"longitude":112.419444,"candidateVendor":"CV. Astana Mas"},
  {"province":"Jawa Timur","regency":"Malang","district":"Sumbermanjing Wetan","village":"Tambakrejo","latitude":-8.431155603,"longitude":112.6863385,"candidateVendor":"CV. Astana Mas"},
  {"province":"Jawa Tengah","regency":"Pati","district":"Dukuhseti","village":"Puncel","latitude":-6.41951239,"longitude":110.9752537,"candidateVendor":"CV. Bumi Jaya Berkah Abadi"},
  {"province":"Jawa Timur","regency":"Banyuwangi","district":"Muncar","village":"Kedungrejo","latitude":-8.432465,"longitude":114.341084,"candidateVendor":"CV. Megah Makmur Konstruksi"},
  {"province":"Jawa Tengah","regency":"Jepara","district":"Mlonggo","village":"Karanggondang","latitude":-6.4866721,"longitude":110.6918188,"candidateVendor":"CV. Permata"},
  {"province":"Jawa Tengah","regency":"Jepara","district":"Kedung","village":"Kedungmalang","latitude":-6.7072316,"longitude":110.6265128,"candidateVendor":"CV. Permata"},
  {"province":"Jawa Tengah","regency":"Jepara","district":"Jepara","village":"Ujungbatu","latitude":-6.582274,"longitude":110.657291,"candidateVendor":"CV. Permata"},
  {"province":"Jawa Tengah","regency":"Jepara","district":"Donorojo","village":"Ujungwatu","latitude":-6.4069446,"longitude":110.9205092,"candidateVendor":"CV. Permata"},
  {"province":"Jawa Tengah","regency":"Jepara","district":"Mlonggo","village":"Mororejo","latitude":-6.5340951,"longitude":110.6653444,"candidateVendor":"CV. Permata"},
  {"province":"Jawa Tengah","regency":"Kebumen","district":"Ayah","village":"Pasir","latitude":-7.7666703,"longitude":109.4371914,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Kebumen","district":"Buayan","village":"Karangbolong","latitude":-7.758204,"longitude":109.46684,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Kebumen","district":"Mirit","village":"Rowo","latitude":-7.806064,"longitude":109.831788,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Pemalang","district":"Pemalang","village":"Danasari","latitude":-6.852778,"longitude":109.409167,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Kota Tegal","district":"Tegal Barat","village":"Tegalsari","latitude":-6.849471,"longitude":109.123925,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Pemalang","district":"Taman","village":"Asemdoyong","latitude":-6.859051,"longitude":109.417304,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Kota Tegal","district":"Tegal Barat","village":"Muarareja","latitude":-6.843333,"longitude":109.107756,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Tengah","regency":"Tegal","district":"Suradadi","village":"Purwahamba","latitude":-6.871103,"longitude":109.252568,"candidateVendor":"CV. Putera Fahlevi"},
  {"province":"Jawa Timur","regency":"Lamongan","district":"Paciran","village":"Kemantren","latitude":-6.871829,"longitude":112.400211,"candidateVendor":"CV. Sapta Manunggal Lestari"},
  {"province":"Jawa Timur","regency":"Lamongan","district":"Brondong","village":"Brondong","latitude":-6.8815657,"longitude":112.210587,"candidateVendor":"CV. Sapta Manunggal Lestari"},
  {"province":"Jawa Timur","regency":"Lamongan","district":"Paciran","village":"Kandangsemangkon","latitude":-6.867731,"longitude":112.319857,"candidateVendor":"CV. Sapta Manunggal Lestari"},
  {"province":"Jawa Timur","regency":"Lamongan","district":"Paciran","village":"Kranji","latitude":-6.875053789,"longitude":112.3800317,"candidateVendor":"CV. Sapta Manunggal Lestari"},
  {"province":"Jawa Timur","regency":"Lamongan","district":"Paciran","village":"Warulor","latitude":-6.881989,"longitude":112.455102,"candidateVendor":"CV. Sapta Manunggal Lestari"},
  {"province":"Jawa Tengah","regency":"Demak","district":"Bonang","village":"Betahwalang","latitude":-6.813204,"longitude":110.586845,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Demak","district":"Wedung","village":"Kedungmutih","latitude":-6.709021,"longitude":110.622617,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Kendal","district":"Rowosari","village":"Gempolsewu","latitude":-6.9052779,"longitude":110.0431284,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Demak","district":"Bonang","village":"Purworejo","latitude":-6.8343659,"longitude":110.5606913,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Kendal","district":"Kendal","village":"Balok","latitude":-6.905524,"longitude":110.206006,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Kota Semarang","district":"Semarang Utara","village":"Tanjung Mas","latitude":-6.945467,"longitude":110.44201,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Tengah","regency":"Demak","district":"Wedung","village":"Kedungkarang","latitude":-6.715347,"longitude":110.644394,"candidateVendor":"CV. Sinar Mulya"},
  {"province":"Jawa Timur","regency":"Situbondo","district":"Besuki","village":"Pesisir","latitude":-7.7276018,"longitude":113.6833622,"candidateVendor":"CV. Tosan"},
  {"province":"Jawa Timur","regency":"Situbondo","district":"Banyuputih","village":"Wonorejo","latitude":-7.9280216,"longitude":114.4183276,"candidateVendor":"CV. Tosan"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Barat","district":"Sekotong","village":"Buwun Mas","latitude":-8.850514,"longitude":116.05314,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Barat","district":"Labuapi","village":"Kuranji Dalang","latitude":-8.6343499,"longitude":116.0734884,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Barat","district":"Sekotong","village":"Batu Putih","latitude":-8.7592421,"longitude":115.8818255,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Kota Mataram","district":"Ampenan","village":"Banjar","latitude":-8.5751873,"longitude":116.0714596,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Plampang","village":"Teluk Santong","latitude":-8.708257,"longitude":117.85654,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Tarano","village":"Labuhan Jambu","latitude":-8.7016824,"longitude":118.0161757,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Alas","village":"Labuhan Alas","latitude":-8.50271,"longitude":117.000097,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Alas Barat","village":"Labuhan Mapin","latitude":-8.524052,"longitude":116.922498,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Buer","village":"Pulau Kaung","latitude":-8.462114,"longitude":117.010232,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Sumbawa","district":"Buer","village":"Labuhan Burung","latitude":-8.451908,"longitude":117.033984,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Tengah","district":"Pujut","village":"Mertak","latitude":-8.880521,"longitude":116.394673,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Tengah","district":"Pujut","village":"Kuta","latitude":-8.89339,"longitude":116.276021,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Timur","district":"Sambelia","village":"Sugian","latitude":-8.336853,"longitude":116.69652,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Nusa Tenggara Barat","regency":"Lombok Barat","district":"Lembar","village":"Lembar Selatan","latitude":-8.719208,"longitude":116.058951,"candidateVendor":"PT. Asuka Engineering Indonesia"},
  {"province":"Jawa Timur","regency":"Bangkalan","district":"Arosbaya","village":"Tengket","latitude":-6.939219,"longitude":112.830416,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Pamekasan","district":"Batumarmar","village":"Tamberu","latitude":-6.89650153,"longitude":113.4845161,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Pamekasan","district":"Pasean","village":"Sotabar","latitude":-6.894211656,"longitude":113.5399314,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Bangkalan","district":"Klampis","village":"Klampis Barat","latitude":-6.893414204,"longitude":112.9031232,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Bangkalan","district":"Klampis","village":"Klampis Timur","latitude":-6.893364068,"longitude":112.9121672,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Bangkalan","district":"Socah","village":"Junganyar","latitude":-7.087461693,"longitude":112.6848031,"candidateVendor":"PT. Elang Mas Berdikari"},
  {"province":"Jawa Timur","regency":"Tulungagung","district":"Besuki","village":"Besole","latitude":-8.257476,"longitude":111.799691,"candidateVendor":"CV Wapike Bali"},
  {"province":"Jawa Timur","regency":"Probolinggo","district":"Dringu","village":"Randuputih","latitude":-7.702861,"longitude":113.479625,"candidateVendor":"CV Wapike Bali"},
  {"province":"Jawa Timur","regency":"Jember","district":"Kencong","village":"Paseban","latitude":-8.3290465,"longitude":113.337692,"candidateVendor":"CV Wapike Bali"},
  {"province":"Jawa Timur","regency":"Jember","district":"Ambulu","village":"Sumberejo","latitude":-8.4383292,"longitude":113.5837641,"candidateVendor":"CV Wapike Bali"},
  {"province":"Jawa Timur","regency":"Tulungagung","district":"Tanggunggunung","village":"Jengglungharjo","latitude":-8.286979,"longitude":111.926247,"candidateVendor":"CV Wapike Bali"},
  {"province":"Jawa Tengah","regency":"Pemalang","district":"Pemalang","village":"Sugihwaras","latitude":-6.86264,"longitude":109.368043,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Jawa Tengah","regency":"Pemalang","district":"Ulujami","village":"Mojo","latitude":-6.811935,"longitude":109.52266,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Jawa Tengah","regency":"Pemalang","district":"Petarukan","village":"Nyamplungsari","latitude":-6.840833,"longitude":109.443985,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Bali","regency":"Jembrana","district":"Jembrana","village":"Air Kuning","latitude":-8.405557,"longitude":114.643027,"candidateVendor":"PT. Sendang Dakara Nusantara"},
  {"province":"Bali","regency":"Buleleng","district":"Gerokgak","village":"Sumberkima","latitude":-8.137572,"longitude":114.599475,"candidateVendor":"PT. Sendang Dakara Nusantara"},
  {"province":"Bali","regency":"Jembrana","district":"Melaya","village":"Candikusuma","latitude":-8.308993,"longitude":114.51901,"candidateVendor":"PT. Sendang Dakara Nusantara"},
  {"province":"Bali","regency":"Karangasem","district":"Manggis","village":"Antiga Kelod","latitude":-8.54419,"longitude":115.496526,"candidateVendor":"PT. Sendang Dakara Nusantara"},
  {"province":"Daerah Istimewa Yogyakarta","regency":"Gunungkidul","district":"Girisubo","village":"Songbanyu","latitude":-8.18705,"longitude":110.801225,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Daerah Istimewa Yogyakarta","regency":"Gunungkidul","district":"Tanjungsari","village":"Banjarejo","latitude":-8.1321154,"longitude":110.5810168,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Daerah Istimewa Yogyakarta","regency":"Gunungkidul","district":"Saptosari","village":"Kanigoro","latitude":-8.119808,"longitude":110.5143413,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Daerah Istimewa Yogyakarta","regency":"Gunungkidul","district":"Tanjungsari","village":"Kemadang","latitude":-8.1286763,"longitude":110.5494743,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Daerah Istimewa Yogyakarta","regency":"Gunungkidul","district":"Tepus","village":"Sidoharjo","latitude":-8.1429211,"longitude":110.604469,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Jawa Tengah","regency":"Rembang","district":"Rembang","village":"Pasar Banggi","latitude":-6.694044,"longitude":111.393102,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Jawa Tengah","regency":"Rembang","district":"Sarang","village":"Karangmangu","latitude":-6.742113,"longitude":111.677061,"candidateVendor":"PT. Kurnia Alam Sentosa"},
  {"province":"Jawa Tengah","regency":"Rembang","district":"Kaliori","village":"Tambakagung","latitude":-6.698127,"longitude":111.237881,"candidateVendor":"PT. Kurnia Alam Sentosa"},
];
